# Generated by Django 5.0.6 on 2024-07-13 08:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(db_index=True, max_length=150, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ref_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transaction_pin', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
